/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ClinicalCaseReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'clinicalCase';
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type SourceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'source';
};

export type ClinicalCase = {
  _id: string;
  _type: 'clinicalCase';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: 'ru' | 'ro' | 'uk';
  translationGroupId?: string;
  translatedFrom?: ClinicalCaseReference;
  primaryDomain?: 'pet' | 'farm' | 'shared';
  medicalOwner?: AuthorReference;
  riskLevel?: 'HIGH' | 'STANDARD' | 'LOW';
  medicalRevision?: number;
  sourceMedicalRevision?: number;
  lastMedicalReview?: string;
  reviewIntervalMonths?: number;
  sources?: Array<
    {
      _key: string;
    } & SourceReference
  >;
  consentVerified?: boolean;
  consentReference?: string;
  anonymisationVerified?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  defaultLanguage?: string;
};

export type Source = {
  _id: string;
  _type: 'source';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  status?: 'current' | 'superseded' | 'withdrawn';
  supersededBy?: SourceReference;
  jurisdiction?: string;
  identifier?: string;
};

export type Topic = {
  _id: string;
  _type: 'topic';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  labels?: {
    ru?: string;
    ro?: string;
    uk?: string;
  };
};

export type Species = {
  _id: string;
  _type: 'species';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  labels?: {
    ru?: string;
    ro?: string;
    uk?: string;
  };
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  language?: 'ru' | 'ro' | 'uk';
  translationGroupId?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'article';
};

export type SpeciesReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'species';
};

export type TopicReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'topic';
};

export type Article = {
  _id: string;
  _type: 'article';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  language?: 'ru' | 'ro' | 'uk';
  translationGroupId?: string;
  translatedFrom?: ArticleReference;
  primaryDomain?: 'pet' | 'farm' | 'shared';
  medicalOwner?: AuthorReference;
  reviewedBy?: AuthorReference;
  riskLevel?: 'HIGH' | 'STANDARD' | 'LOW';
  medicalRevision?: number;
  sourceMedicalRevision?: number;
  lastMedicalReview?: string;
  reviewIntervalMonths?: number;
  sources?: Array<
    {
      _key: string;
    } & SourceReference
  >;
  species?: Array<
    {
      _key: string;
    } & SpeciesReference
  >;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  previousSlugs?: Array<string>;
  archived?: boolean;
  withdrawn?: boolean;
  replacement?: ArticleReference;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ClinicalCaseReference
  | AuthorReference
  | SourceReference
  | ClinicalCase
  | SiteSettings
  | Source
  | Topic
  | Species
  | Page
  | Slug
  | ArticleReference
  | SpeciesReference
  | TopicReference
  | Article
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    _id,    title,    defaultLanguage  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: 'siteSettings';
  title: string | null;
  defaultLanguage: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PAGE_BY_TRANSLATION_GROUP_QUERY
// Query: *[    _type == "page" &&    translationGroupId == $translationGroupId &&    language == $language &&    defined(slug.current)  ][0]{    _id,    title,    "slug": slug.current,    language,    translationGroupId,    body  }
export type PAGE_BY_TRANSLATION_GROUP_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  language: 'ro' | 'ru' | 'uk' | null;
  translationGroupId: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    _id,\n    title,\n    defaultLanguage\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[\n    _type == "page" &&\n    translationGroupId == $translationGroupId &&\n    language == $language &&\n    defined(slug.current)\n  ][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    language,\n    translationGroupId,\n    body\n  }\n': PAGE_BY_TRANSLATION_GROUP_QUERY_RESULT;
  }
}
