/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SafetyNotice = {
  _type: 'safetyNotice';
  title?: string;
  text?: string;
};

export type NextSteps = {
  _type: 'nextSteps';
  title?: string;
  items?: Array<string>;
};

export type Checklist = {
  _type: 'checklist';
  title?: string;
  items?: Array<string>;
};

export type RedFlagCategory = {
  _type: 'redFlagCategory';
  title?: string;
  description?: string;
  items?: Array<string>;
};

export type DontDoBlock = {
  _type: 'dontDoBlock';
  title?: string;
  items?: Array<string>;
};

export type PracticalActions = {
  _type: 'practicalActions';
  title?: string;
  items?: Array<string>;
};

export type ClinicalCaseReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'clinicalCase';
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type SourceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'source';
};

export type ClinicalCase = {
  _id: string;
  _type: 'clinicalCase';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: 'ru' | 'ro' | 'uk';
  translationGroupId?: string;
  translatedFrom?: ClinicalCaseReference;
  primaryDomain?: 'pet' | 'farm' | 'shared';
  medicalOwner?: AuthorReference;
  riskLevel?: 'HIGH' | 'STANDARD' | 'LOW';
  medicalRevision?: number;
  lastMedicalReview?: string;
  reviewIntervalMonths?: number;
  sources?: Array<
    {
      _key: string;
    } & SourceReference
  >;
  consentVerified?: boolean;
  consentReference?: string;
  anonymisationVerified?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  defaultLanguage?: string;
};

export type Source = {
  _id: string;
  _type: 'source';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  status?: 'current' | 'superseded' | 'withdrawn';
  supersededBy?: SourceReference;
  jurisdiction?: string;
  identifier?: string;
};

export type Topic = {
  _id: string;
  _type: 'topic';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  labels?: {
    ru?: string;
    ro?: string;
    uk?: string;
  };
};

export type Species = {
  _id: string;
  _type: 'species';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  labels?: {
    ru?: string;
    ro?: string;
    uk?: string;
  };
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  language?: 'ru' | 'ro' | 'uk';
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'article';
};

export type SpeciesReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'species';
};

export type TopicReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'topic';
};

export type Article = {
  _id: string;
  _type: 'article';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  summary?: string;
  slug?: Slug;
  language?: 'ru' | 'ro' | 'uk';
  translationGroupId?: string;
  translatedFrom?: ArticleReference;
  primaryDomain?: 'pet' | 'farm' | 'shared';
  medicalOwner?: AuthorReference;
  reviewedBy?: AuthorReference;
  riskLevel?: 'HIGH' | 'STANDARD' | 'LOW';
  medicalRevision?: number;
  sourceMedicalRevision?: number;
  lastMedicalReview?: string;
  reviewIntervalMonths?: number;
  reviewNotes?: string;
  sources?: Array<
    {
      _key: string;
    } & SourceReference
  >;
  species?: Array<
    {
      _key: string;
    } & SpeciesReference
  >;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & PracticalActions)
    | ({
        _key: string;
      } & DontDoBlock)
    | ({
        _key: string;
      } & RedFlagCategory)
    | ({
        _key: string;
      } & Checklist)
    | ({
        _key: string;
      } & NextSteps)
    | ({
        _key: string;
      } & SafetyNotice)
  >;
  previousSlugs?: Array<string>;
  archived?: boolean;
  withdrawn?: boolean;
  replacement?: ArticleReference;
  seoTitle?: string;
  seoDescription?: string;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SafetyNotice
  | NextSteps
  | Checklist
  | RedFlagCategory
  | DontDoBlock
  | PracticalActions
  | ClinicalCaseReference
  | AuthorReference
  | SourceReference
  | ClinicalCase
  | SiteSettings
  | Source
  | Topic
  | Species
  | Page
  | Slug
  | ArticleReference
  | SpeciesReference
  | TopicReference
  | Article
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: queries/article.ts
// Variable: publishedArticlePathsQuery
// Query: *[_type == "article" && language == "ru" && defined(slug.current) && !archived && !withdrawn &&    defined(title) && defined(summary) && defined(medicalOwner) && defined(riskLevel) &&    defined(medicalRevision) && defined(lastMedicalReview) && defined(reviewIntervalMonths) && count(sources) > 0 && count(body) > 0]  { "slug": slug.current, language, primaryDomain }
export type PublishedArticlePathsQueryResult = Array<{
  slug: string | null;
  language: 'ro' | 'ru' | 'uk' | null;
  primaryDomain: 'farm' | 'pet' | 'shared' | null;
}>;

// Source: queries/article.ts
// Variable: publishedArticleDetailQuery
// Query: *[_type == "article" && language == $language && slug.current == $slug][0]{    _id, title, summary, "slug": slug.current, language, translationGroupId, primaryDomain,    medicalOwner->{ _id, name, role }, reviewedBy->{ _id, name, role }, riskLevel,    medicalRevision, sourceMedicalRevision, lastMedicalReview, reviewIntervalMonths, reviewNotes,    sources[]->{ _id, title, url, status, jurisdiction, identifier, supersededBy->{ _id, title, url } },    species[]->{ _id, name }, topics[]->{ _id, name }, body[]{ _key, _type, ..., children[]{ _key, _type, text, marks, markDefs } },    archived, withdrawn, replacement->{ _id, title, "slug": slug.current, primaryDomain, language },    translatedFrom->{ _id, medicalRevision }, previousSlugs, seoTitle, seoDescription  }
export type PublishedArticleDetailQueryResult = {
  _id: string;
  title: string | null;
  summary: string | null;
  slug: string | null;
  language: 'ro' | 'ru' | 'uk' | null;
  translationGroupId: string | null;
  primaryDomain: 'farm' | 'pet' | 'shared' | null;
  medicalOwner: {
    _id: string;
    name: string | null;
    role: string | null;
  } | null;
  reviewedBy: {
    _id: string;
    name: string | null;
    role: string | null;
  } | null;
  riskLevel: 'HIGH' | 'LOW' | 'STANDARD' | null;
  medicalRevision: number | null;
  sourceMedicalRevision: number | null;
  lastMedicalReview: string | null;
  reviewIntervalMonths: number | null;
  reviewNotes: string | null;
  sources: Array<{
    _id: string;
    title: string | null;
    url: string | null;
    status: 'current' | 'superseded' | 'withdrawn' | null;
    jurisdiction: string | null;
    identifier: string | null;
    supersededBy: {
      _id: string;
      title: string | null;
      url: string | null;
    } | null;
  }> | null;
  species: Array<{
    _id: string;
    name: string | null;
  }> | null;
  topics: Array<{
    _id: string;
    name: string | null;
  }> | null;
  body: Array<
    | {
        _key: string;
        _type: 'block';
        children: Array<{
          _key: string;
          _type: 'span';
          text: string | null;
          marks: Array<string> | null;
          markDefs: null;
        }> | null;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
      }
    | {
        _key: string;
        _type: 'checklist';
        title?: string;
        items?: Array<string>;
        children: null;
      }
    | {
        _key: string;
        _type: 'dontDoBlock';
        title?: string;
        items?: Array<string>;
        children: null;
      }
    | {
        _key: string;
        _type: 'nextSteps';
        title?: string;
        items?: Array<string>;
        children: null;
      }
    | {
        _key: string;
        _type: 'practicalActions';
        title?: string;
        items?: Array<string>;
        children: null;
      }
    | {
        _key: string;
        _type: 'redFlagCategory';
        title?: string;
        description?: string;
        items?: Array<string>;
        children: null;
      }
    | {
        _key: string;
        _type: 'safetyNotice';
        title?: string;
        text?: string;
        children: null;
      }
  > | null;
  archived: boolean | null;
  withdrawn: boolean | null;
  replacement: {
    _id: string;
    title: string | null;
    slug: string | null;
    primaryDomain: 'farm' | 'pet' | 'shared' | null;
    language: 'ro' | 'ru' | 'uk' | null;
  } | null;
  translatedFrom: {
    _id: string;
    medicalRevision: number | null;
  } | null;
  previousSlugs: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: queries/article.ts
// Variable: eligibleKnowledgeQuery
// Query: *[_type == "article" && defined(slug.current) && !archived && !withdrawn && language == $language &&    !(riskLevel == "HIGH" && (withdrawn == true || !defined(lastMedicalReview) || count(sources[@->status in ["withdrawn"]]) > 0))]  | order(title asc){ _id, title, summary, "slug": slug.current, language, primaryDomain }
export type EligibleKnowledgeQueryResult = Array<{
  _id: string;
  title: string | null;
  summary: string | null;
  slug: string | null;
  language: 'ro' | 'ru' | 'uk' | null;
  primaryDomain: 'farm' | 'pet' | 'shared' | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "article" && language == "ru" && defined(slug.current) && !archived && !withdrawn &&\n    defined(title) && defined(summary) && defined(medicalOwner) && defined(riskLevel) &&\n    defined(medicalRevision) && defined(lastMedicalReview) && defined(reviewIntervalMonths) && count(sources) > 0 && count(body) > 0]\n  { "slug": slug.current, language, primaryDomain }\n': PublishedArticlePathsQueryResult;
    '\n  *[_type == "article" && language == $language && slug.current == $slug][0]{\n    _id, title, summary, "slug": slug.current, language, translationGroupId, primaryDomain,\n    medicalOwner->{ _id, name, role }, reviewedBy->{ _id, name, role }, riskLevel,\n    medicalRevision, sourceMedicalRevision, lastMedicalReview, reviewIntervalMonths, reviewNotes,\n    sources[]->{ _id, title, url, status, jurisdiction, identifier, supersededBy->{ _id, title, url } },\n    species[]->{ _id, name }, topics[]->{ _id, name }, body[]{ _key, _type, ..., children[]{ _key, _type, text, marks, markDefs } },\n    archived, withdrawn, replacement->{ _id, title, "slug": slug.current, primaryDomain, language },\n    translatedFrom->{ _id, medicalRevision }, previousSlugs, seoTitle, seoDescription\n  }\n': PublishedArticleDetailQueryResult;
    '\n  *[_type == "article" && defined(slug.current) && !archived && !withdrawn && language == $language &&\n    !(riskLevel == "HIGH" && (withdrawn == true || !defined(lastMedicalReview) || count(sources[@->status in ["withdrawn"]]) > 0))]\n  | order(title asc){ _id, title, summary, "slug": slug.current, language, primaryDomain }\n': EligibleKnowledgeQueryResult;
  }
}
